[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd standalone && npm install"]

[phases.build]
cmds = ["cd standalone && npm run build"]

[start]
cmd = "cd standalone && npm run start"

